#!/bin/bash
#chkconfig: 345 72 34
#description: cmsweb_conddb-appserver This script runs CMS CondDB APP service

if [ -z ${CONDAPP_VERSION} ]; then
   echo $"The CondDB APP environment is not set" 2>&1 1>& /dev/null < /dev/null &
   . /data/projects/conddb-appserver/setup.sh
fi

RETVAL=$?

cmd=$CONDDB_APPSERVER_ROOT/etc/init.d/conddb-app-server

start(){
    su cmsweb -c "nohup ${cmd} start 2>&1 1>& /dev/null < /dev/null &"
}
stop(){
    su cmsweb -c "nohup ${cmd} stop 2>&1 1>& /dev/null < /dev/null &"
}
restart(){
    su cmsweb -c "nohup ${cmd} restart 2>&1 1>& /dev/null < /dev/null &"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    restart
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
    ;;
esac

exit $RETVAL
