#!/bin/bash
#chkconfig: 345 71 32
#description: cmsweb_sitedb This script runs CMS SiteDB service

if [ -z ${SITEDB_VERSION} ]; then
   echo $"The SiteDB environment is not set" 2>&1 1>& /dev/null < /dev/null &
   . /data/projects/sitedb/setup.sh production
fi

RETVAL=$?

port=$SITEDB_PORT
pid=`ps auxw | grep cmsWeb | grep -v grep | grep ${port} | awk '{print $2}'`
base=$SITEDB_BASE
cmd=$SITEDB_CMD

start(){
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
    echo $"Start SiteDB Service on port ${port}..."
        su cmsweb -c "nohup ${cmd} 2>&1 1>& /dev/null < /dev/null &"
}
stop(){
    echo $"Stop SiteDB Service on port ${port}..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
}
restart(){
    echo $"Checking for existing cmsWeb app running sitedb..."
        if [ ! -z ${pid} ]; then
          echo $"Found sitedb running on pid=${pid}, will restart"
          kill -9 ${pid}
        fi
    echo $"Start SiteDB Service on port ${port}..."
        su cmsweb -c "nohup ${cmd} 2>&1 1>& /dev/null < /dev/null &"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    restart
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
    ;;
esac

exit $RETVAL
