#!/bin/bash
#chkconfig: 345 76 37
#description: cmsweb_prodmon This script runs CMS ProdMon service

if [ -z ${PRODMON_VERSION} ]; then
   echo $"The ProdMon environment is not set" 2>&1 1>& /dev/null < /dev/null &
   . /data/projects/prodmon/setup.sh prod
fi

RETVAL=$?

port=$PRODMON_PORT
pid=`ps auxw | grep cmsWeb | grep -v grep | grep ${port} | awk '{print $2}'`
base=$PRODMON_BASE
cmd=$PRODMON_CMD

start(){
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
    echo $"Start ProdMon Service on port ${port}..."
        su cmsweb -c "nohup ${cmd} 2>&1 1>& /dev/null < /dev/null &"
}
stop(){
    echo $"Stop ProdMon Service on port ${port}..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
}
restart(){
    echo $"Checking for existing cmsWeb app running prodmon..."
        if [ ! -z ${pid} ]; then
          echo $"Found prodmon running on pid=${pid}, will restart"
          kill -9 ${pid}
        fi
    echo $"Start ProdMon Service on port ${port}..."
        su cmsweb -c "nohup ${cmd} 2>&1 1>& /dev/null < /dev/null &"
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    restart
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
    ;;
esac

exit $RETVAL
