#!/usr/bin/env perl
BEGIN { use strict; use warnings; $^W=1; }
use CGI qw(param header);

print header(-type=>'text/plain'),
      "Environment:\n",
      (map { "$_ = $ENV{$_}\n" } sort keys %ENV), "\n",

      "Parameters:\n",
      (map { "$_ = @{[param($_)]}\n" } param());
exit(0);
